spring.application.name=movier

server.servlet.context-path=/api

jwt.secret=8f42a73054b1749f8f58848be5e6502c526649c9c4a04a5a9a5a2f6e8a5b5c9
jwt.expiration=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/movier
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect